### ISSUE TITLE
get-mailbox statistics issue with error

### ISSUE THREAD

**Issue by meddie-samuel** [Canthv0/RobustCloudCommand#2]
I am trying to run something like this 

Start-RobustCloudCommand -recipients $mbx -ScriptBlock { Get-MailboxStatistics -archive | Select-Object displayname,TotalItemSize,itemcount} -Credential get-credential }

but because the mailbox does not Have an archive mailbox, it keeps restarting for the same user.
If I set the erroraction to continue/ignore, nothing is working,

**Comment by gabymuntean** [comment]
Hello Samuel,

did you try removing the -archive parameter and try again?

**Comment by meddie-samuel** [comment]
Yes - i ended up modifying the script to only include users with -archivestatus enabled.
Different approach and powershell v2 sped up the proces.s
